### ISSUE TITLE
Unable to upgrade to token-registry v5 with trustvc

### ISSUE THREAD

**Issue by ShadyAkhtar** [TrustVC/trustvc#28]
Issue:
Unable to upgrade from `trade-trsust/token-registry@v5` to `@trustvc/trustvc`

Description:
we are currently using trade-trust token registry  and able to upgrade to v5 successfully with tradetrust token-registry@v5, but while upgrading with trustvc we are not able to use any of the function from trustvc. 

example:
**[working code @tradetrust-tt/token-registry@v5]**

    import { wrapDocument } from '@tradetrust-tt/tradetrust';
    .
    .
    .
    const wrappedDocument = wrapDocument(rawDocument);
    
**[Breaking Code with @trustvc/trustvc]**

    import { wrapOADocument as wrapDocument } from '@trustvc/trustvc';
    .
    .
    .
    const wrappedDocument = await wrapDocument(rawDocument);

**Error Screenshot:**
![image](https://github.com/user-attachments/assets/d83298a1-df32-4401-a5b3-e5f3e6c6b279)

![image](https://github.com/user-attachments/assets/bba8725e-c6ef-49de-824e-cee4a9163655)

Error String:

✘ [ERROR] No matching export in "node_modules/@trustvc/w3c-vc/dist/esm/index.js" for import "RawVerifiableCredential"

    node_modules/@trustvc/trustvc/dist/esm/w3c/types.js:1:9:
      1 │ export { RawVerifiableCredential, SignedVerifiableCredential, SigningResult, VerificationResult } from '@trustvc/w3c-vc';
        ╵          ~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/@trustvc/w3c-vc/dist/esm/index.js" for import "SignedVerifiableCredential"

    node_modules/@trustvc/trustvc/dist/esm/w3c/types.js:1:34:
      1 │ export { RawVerifiableCredential, SignedVerifiableCredential, SigningResult, VerificationResult } from '@trustvc/w3c-vc';
        ╵                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/@trustvc/w3c-vc/dist/esm/index.js" for import "SigningResult"

    node_modules/@trustvc/trustvc/dist/esm/w3c/types.js:1:62:
      1 │ export { RawVerifiableCredential, SignedVerifiableCredential, SigningResult, VerificationResult } from '@trustvc/w3c-vc';
        ╵                                                               ~~~~~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/@trustvc/w3c-vc/dist/esm/index.js" for import "VerificationResult"

    node_modules/@trustvc/trustvc/dist/esm/w3c/types.js:1:77:
      1 │ export { RawVerifiableCredential, SignedVerifiableCredential, SigningResult, VerificationResult } from '@trustvc/w3c-vc';
        ╵                                                                              ~~~~~~~~~~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/@trustvc/w3c-issuer/dist/esm/index.js" for import "PrivateKeyPair"

    node_modules/@trustvc/trustvc/dist/esm/w3c/types.js:2:9:
      2 │ export { PrivateKeyPair } from '@trustvc/w3c-issuer';
        ╵          ~~~~~~~~~~~~~~

[ESLint] Found 0 error and 0 warning
/home/shakespear/work/trade-trust/mletr-solution/frontend/node_modules/esbuild/lib/main.js:1649
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 5 errors:
node_modules/@trustvc/trustvc/dist/esm/w3c/types.js:1:9: ERROR: No matching export in "node_modules/@trustvc/w3c-vc/dist/esm/index.js" for import "RawVerifiableCredential"
node_modules/@trustvc/trustvc/dist/esm/w3c/types.js:1:34: ERROR: No matching export in "node_modules/@trustvc/w3c-vc/dist/esm/index.js" for import "SignedVerifiableCredential"
node_modules/@trustvc/trustvc/dist/esm/w3c/types.js:1:62: ERROR: No matching export in "node_modules/@trustvc/w3c-vc/dist/esm/index.js" for import "SigningResult"
node_modules/@trustvc/trustvc/dist/esm/w3c/types.js:1:77: ERROR: No matching export in "node_modules/@trustvc/w3c-vc/dist/esm/index.js" for import "VerificationResult"
node_modules/@trustvc/trustvc/dist/esm/w3c/types.js:2:9: ERROR: No matching export in "node_modules/@trustvc/w3c-issuer/dist/esm/index.js" for import "PrivateKeyPair"
    at failureErrorWithLog (/home/shakespear/work/trade-trust/mletr-solution/frontend/node_modules/esbuild/lib/main.js:1649:15)
    at /home/shakespear/work/trade-trust/mletr-solution/frontend/node_modules/esbuild/lib/main.js:1058:25
    at /home/shakespear/work/trade-trust/mletr-solution/frontend/node_modules/esbuild/lib/main.js:1525:9
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 9,
        file: 'node_modules/@trustvc/trustvc/dist/esm/w3c/types.js',
        length: 23,
        line: 1,
        lineText: "export { RawVerifiableCredential, SignedVerifiableCredential, SigningResult, VerificationResult } from '@trustvc/w3c-vc';",
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'No matching export in "node_modules/@trustvc/w3c-vc/dist/esm/index.js" for import "RawVerifiableCredential"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 34,
        file: 'node_modules/@trustvc/trustvc/dist/esm/w3c/types.js',
        length: 26,
        line: 1,
        lineText: "export { RawVerifiableCredential, SignedVerifiableCredential, SigningResult, VerificationResult } from '@trustvc/w3c-vc';",
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'No matching export in "node_modules/@trustvc/w3c-vc/dist/esm/index.js" for import "SignedVerifiableCredential"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 62,
        file: 'node_modules/@trustvc/trustvc/dist/esm/w3c/types.js',
        length: 13,
        line: 1,
        lineText: "export { RawVerifiableCredential, SignedVerifiableCredential, SigningResult, VerificationResult } from '@trustvc/w3c-vc';",
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'No matching export in "node_modules/@trustvc/w3c-vc/dist/esm/index.js" for import "SigningResult"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 77,
        file: 'node_modules/@trustvc/trustvc/dist/esm/w3c/types.js',
        length: 18,
        line: 1,
        lineText: "export { RawVerifiableCredential, SignedVerifiableCredential, SigningResult, VerificationResult } from '@trustvc/w3c-vc';",
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'No matching export in "node_modules/@trustvc/w3c-vc/dist/esm/index.js" for import "VerificationResult"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 9,
        file: 'node_modules/@trustvc/trustvc/dist/esm/w3c/types.js',
        length: 14,
        line: 2,
        lineText: "export { PrivateKeyPair } from '@trustvc/w3c-issuer';",
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'No matching export in "node_modules/@trustvc/w3c-issuer/dist/esm/index.js" for import "PrivateKeyPair"'
    }
  ],
  warnings: []
}

**Comment by nghaninn** [comment]
Hi @ShadyAkhtar 
A new update has been release. Do let us know if that resolves the issue that you are facing.
Thanks for taking the time to look into this issue.

**Comment by ShadyAkhtar** [comment]
yeah partially resolved, we are unable to fetch the endorsementChain.
    
    import { ethers, providers } from 'ethers';
    
    useEffect(() => {
    resourcePersistence.set('currentNetwork', currentNetwork);
    const magicSDK = initializeMagicSDK();
    setMagic(magicSDK);

    const provider = new ethers.providers.Web3Provider((magicSDK as any).rpcProvider);
    const fallbackProvider = new providers.JsonRpcProvider(
      getChainInfoByChainId(currentNetwork).rpcUrl
    );
    // const fallbackProvider = utils.generateProvider({
    //   url: getChainInfoByChainId(currentNetwork).rpcUrl
    // });
    console.log('🚀 ~ useEffect ~ fallbackProvider:', fallbackProvider);
    // const provvvv = new ethers.providers.Web3Provider(fallbackProvider as any);
    setFallbackProvider(fallbackProvider);
    // Set Gas Price for all transactions

    setEthersProvider(provider);

    const networkRPC = getChainInfoByChainId(currentNetwork).rpcUrl;
    setReadOnlyWeb3(new Web3(networkRPC ? networkRPC : 'https://erpc.apothem.network/'));
     }, [currentNetwork]);

> Fetch Endorsement Chain using @trustvc/trustvc

    import { fetchEndorsementChain } from '@trustvc/trustvc';
    const _fetchEndorsementChain = async () => {
    if (tokenRegistry && tokenId && fallbackProvider) {
      console.log('💁', tokenRegistry, ethersProvider, fallbackProvider);
      const endorsementChain = await fetchEndorsementChain(
        tokenRegistry,
        tokenId,
        ethersProvider as Provider
      );
      console.log('👉️ ~ useEffect ~ endorsementChain:', endorsementChain);
    }
    };

    useEffect(() => {
      const res = _fetchEndorsementChain();
      console.log('✅ ~ useEffect ~ res:', res);
     }, [tokenRegistry, tokenId, fallbackProvider]);

----------------------------------------

No response from the `fetchEndorsementChain` function

----------------------------------------
ethers version: 5.7.2
@trustvc/trustvc version: 1.1.1

BL transferrable file (stability testnet) 👇️:
[BL_V5.json](https://github.com/user-attachments/files/18252702/BL_V5.json)

**Comment by ShadyAkhtar** [comment]
# Issue: Unable to Fetch Endorsement Chain Using `fetchEndorsementChain`

## Issue Summary

We encountered an issue while attempting to fetch the endorsement chain using the `fetchEndorsementChain` function from the `@trustvc/trustvc` library. The function did not return any response.

## Environment Details

- **ethers version:** 5.7.2
- **@trustvc/trustvc version:** 1.1.1
- **Network:** Stability Testnet  
- **Token Registry:** BL_V5.json (transferrable file)

## Root Cause

The issue was caused by a version conflict between the `ethers` library used in our project (`5.7.2`) and a sub-dependency of the `@trustvc/trustvc` library, which required `ethers` version `7.x`. This mismatch led to runtime issues.

## Solution

We resolved the issue by overriding the `ethers` version in our `package.json` to ensure all dependencies use the same compatible version (`5.7.2`).

### Updated `package.json`

```json
{
  "overrides": {
    "ethers": "^5.7.2"
  }
}

```
## Steps Taken

### 1. Add Overrides to package.json:
Added the overrides property in package.json to force the ethers version across all dependencies.

### 2. Remove Existing Node Modules:
Deleted the node_modules folder and package-lock.json to ensure a clean slate:

```bash
rm -rf node_modules package-lock.json
```

### 3. Reinstall Dependencies:
Reinstalled all dependencies to apply the updated overrides configuration:
```bash
npm install

```

### 4. Verify Resolution:
Checked that the ethers version conflict was resolved and the fetchEndorsementChain function returned the expected response.
